---
title: "Research"
slug: research
citeproc: true
output:
  blogdown::html_page:
      toc: TRUE
---

### Working Papers

<p><strong>The Political Consequences of "Source Country" Operations: Evidence from Crop Eradication in Mexico</strong><br>\[[paper](/files/papers/crops/paper.pdf){target="_blank"}\]\[[appendix](/files/papers/crops/appendix.pdf){target="_blank"}\]</p>
<p><em>R&R AJPS</em></p>
::: grid
::: g-col-12
<p style="font-size: 15px; text-align: justify;">

When crafting law enforcement policy, drug-producing --- or "source" --- countries must adjudicate between domestic preferences and international pressure to curb supply. What are the political consequences of prioritizing supply-reduction? I analyze illicit-crop eradication in Mexico, where the army routinely incinerates fields to ensure continued US aid. Small, marginalized crop-growing communities regard eradication as an unjust federal policy. However, the importance of aid makes the policy inelastic. Because eradication policy is never on the electoral menu, I theorize that eradication decreases trust in the government and reduces turnout instead of engendering electoral backlash. To test, I create a novel eradication measure at the electoral precinct level using data from 50,000 satellite-detected fields and NASA's satellite-collected fire data. Using variation in location and timing, I show that eradication depresses turnout in federal elections and trust in the army. By divorcing domestic electoral politics from policy, US security aid may undermine accountability.

</p>
:::
:::

<p><strong>Political Science Under Pressure: Competition and Collaboration in an Evolving Discipline, 2003-2023</strong><br/> with Guy Grossman and Will Dinneen <br /> \[[paper](/files/papers/landscape/landscape.pdf){target="_blank"}\]</p>
<p><em>R&R PS</em></p>
::: grid
::: g-col-12
<p style="font-size: 15px; text-align: justify;">

This study analyzes 140,000+ articles from 174 political science journals (2003-2023) to understand how structural incentives have shaped scholarly production in the discipline. We examine changes in publication volume, researcher productivity, topical content, methodological approaches, and collaboration patterns over two decades. Publication volume tripled, driven by three times more authors and small productivity gains. Further, since 2021, most papers have been co-authored, with teams producing topically more novel research than solo authors. Quantitative methods increasingly dominate, especially in top journals. We also find that, despite paper-level specialization, the discipline maintains topical diversity. Novel research—particularly from all-female teams—receives more citations long-term but appears less frequently in top journals. Overall, political science has transformed into a larger, more collaborative, and more quantitative discipline. Yet these changes occur amid job market contraction and mounting publication pressures that may require researchers to sacrifice career stability and intellectual risk-taking for productivity metrics.

</p>
:::
:::

<p><strong>The Demobilizing Effect of Violence: Evidence of Heterogeneous Exposure and Response</strong><br /> Draft Available Upon Request</p>
<p><em>Honorable Mention for the APSA Comparative Politics Section Sage Best Paper Award (2024)</em></p>

::: grid
::: g-col-12
<p style="font-size: 15px; text-align: justify;">

Theoretical accounts of the participatory effects of violence suggest it demobilizes some individuals but mobilizes others, making exposure patterns critical for understanding consequences. I develop a principal stratification framework incorporating heterogeneous treatment probabilities to assess the implications of accounting for systematic over/underexposure to violence. Empirically, I focus on criminal violence. Work targeting average treatment effects shows crime spurs participation. However, criminology research suggests that people are heterogeneously vulnerable to crime. Using survey data from 150,000 Latin Americans, panel data from Mexico, and millions of simulations, I demonstrate that individuals who participate less post-victimization are more likely to become victims, resulting in an overall negative change of non-electoral participation due to crime. Similar patterns emerge when reassessing results from civil war exposure and police contact. These results challenge our understanding of violence's political consequences and highlight the distinction between how violence could shape politics and how, in fact, it does so.

</p>
:::
:::

<p><strong>Class and the Development of Trust in Police in Latin America</strong><br/> 
with Tara Slough <br /> 
\[[paper](/files/papers/trust/paper.pdf){target="_blank"}\]\[[appendix](/files/papers/trust/appendix.pdf){target="_blank"}\]</p>
<p><em>Under Review</em></p>

::: grid
::: g-col-12
<p style="font-size: 15px; text-align: justify;">
Trust in police is a critical input in the co-production of public security. We show that the 
positive socioeconomic status (SES)-trust in police gradient observed in the US does not 
generalize to Latin America. In 146 surveys spanning 20 countries, we find that trust in police 
is weakly and negatively correlated with SES—a fact that neither regional nor subject-matter 
experts anticipated. We propose that rich citizens are more likely to interpret everyday 
experiences as signals about the police. Because bad experiences like crime victimization and 
bribe solicitation are more common in Latin America than in the US, rich citizens's tendency 
to interpret poor security outcomes as signals of police untrustworthiness leads to a lower trust–
SES gradient. In our account, cross-country differences in the trust–SES gradient are driven by 
differences in policing outcomes coupled with universal class-based differences in people's 
readiness to see the world around them as signals about police.
</p>
:::
:::

<p><strong>Informal Connections Outweigh Co-authorship Ties in Academic Impact</strong><br/> 
with Lluís Danús, Will Dinneen, Guy Grossman, and Sandra González-Bailón<br /> 
</p>
<p><em>Under Review</em></p>

::: grid
::: g-col-12
<p style="font-size: 15px; text-align: justify;">
Research has documented the importance of teamwork in the form of co-authorship for research productivity and innovation, but we know much less about how informal collaborations relate to academic success. Informal ties allow intangible exchanges like mentoring, guidance, and feedback to flow among scholars: these interactions weave a support structure that improves ideas and encourages project growth. However, these informal exchanges are more difficult to measure because they do not leave as clear a trail as co-authorship ties. Here, we uncover this layer of informal communication around scholarly outputs by parsing the information contained in the acknowledgment sections of published articles. Our data include 130,000 articles authored by 86,000 scholars from the period 2003-2023. We analyze scholars’ embeddedness in this informal structure of collaboration and reveal that (1) informal ties create a larger and denser network of support than co-authorship ties; (2) disconnection from informal networks is associated with gaps in productivity and impact; and (3) informal ties are a more relevant predictor of academic success than formal collaborations, even after matching for gender, seniority, methodology, and geographical location. Using coarsened exact matching and random forest regressions we show that informal structures of support are significantly associated with academic impact, creating gaps in who benefits from those connections.
</p>
:::
:::



### Works-in-Progress

<p><strong>Endogenous information consumption and behavioral changes</strong><br /> with Kun Heo and Elisa Wirsching<br /></p>

::: grid
::: g-col-12
<p style="font-size: 15px;  text-align: justify;">

Common wisdom expectations and extant observational research suggest that information is a central shaping force of the political process. Yet, experimental results repeatedly show that providing information to individuals — whether about a candidate's policy platform, a politician's misuse of public funds, or public service provision — may result in small or no changes in citizens' political behavior. We provide a framework that disciplines the conceptual understanding of information as central to citizens' decision-making with these seemingly disjoint results by focusing on the endogenous consumption and provision of information. Using a formal model, we show that the people whose behavior is most elastic to learning have likely self-selected into learning more in the past and have interim posterior beliefs with smaller variances relative to the rest of the population. Alternatively, the people whose behavior is least elastic to learning have incentives to self-select into consuming new information the least. While these latter groups will have less certain beliefs, they will also be less likely to modify their behavior due to learning new information.

</p>
:::
:::

<p><strong>Reducing WhatsApp Usage to Mitigate Misinformation Exposure During Elections: Evidence from a Multi-Country Experiment</strong><br /> with Rajeshwari Majumdar, Tiago Ventura, Shelley Liu, and Joshua Tucker<br/></p>

::: grid
::: g-col-12
<p style="font-size: 15px;  text-align: justify;">

Recent scholarly work has investigated how social media platforms increase users' exposure to misinformation and harmful content, contributing to contemporary democratic ills such as increased levels of polarization, intergroup prejudice, and offline violence. This paper presents two distinct interventions to identify the causal effects of the most heavily used social media messaging app in the world – WhatsApp – on exposure to online misinformation and its downstream effects on political attitudes. We deploy simultaneous field experiments in India and South Africa, incentivizing participants to either (1) reduce exposure to multimedia on WhatsApp or (2) limit overall WhatsApp usage to up to 10 minutes per day for four weeks ahead of their 2024 general elections. Our intervention significantly reduced participants’ exposure to false rumors circulating widely during the election and to overall political news. These changes in the informational environment, however, did not significantly change belief accuracy. We also detected a significant reduction in ethnic-based prejudice in India when participants reduced their overall WhatsApp usage, but estimated precise nulls for polarization outcomes in South Africa

</p>
:::
:::
