---
title: "Teaching"
slug: teaching
sidebar: true
toc: true
---

### University of Pennsylvania

At UPenn, I will co-teach PSCI3200 - Global Development: Intermediate Topics in Politics, Policy, and Data with Jeremy Springman in Spring 2025. Materials for the course and source code are available on the 2024 course website: [jrspringman.github.io/psci3200-globaldev/](https://jrspringman.github.io/psci3200-globaldev/)

### New York University

-   **Comparative Politics (Undergraduate)**

    -  TA for Professor Rahsaan Maxwell, Fall 2023. \[[Course Evaluations](/files/course_evals/comparative_rm.pdf){target="_blank"}\]

-   **Comparative Politics (Undergraduate)**

    -   TA for Professor Gwyneth McClendon, Spring 2023. \[[Course Evaluations](/files/course_evals/comparative_gm.pdf){target="_blank"}\]

-   **Quantitative Methods III (Graduate)**

    -   TA for Professor Tara Slough, Fall 2022

-   **Intro to Quantitative Political Analysis II (Graduate)**

    -  TA for Professor Gizem Acikgoz, Spring 2022

-   **Intro to Quantitative Political Analysis I (Graduate)**

    -   TA for Professor Gizem Acikgoz, Fall 2021

-   **Introduction to Research Methods (Undergraduate)**

    -  TA for Professor Anna Harvey, Spring 2021. \[[Course Evaluations](/files/course_evals/methods_anna.pdf){target="_blank"}\]

```{=html}
<!-- -->
```
-   **Political Theory** **(Undergraduate)**

    -   For Professor Dimitri Landa, Fall 2020. \[[Course Evaluations](/files/course_evals/theory.pdf){target="_blank"}\]



### 
